# Generated by Django 5.1.6 on 2025-06-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_county_options_alter_footersettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='rules',
            field=models.TextField(blank=True, help_text='Regulile și restricțiile pentru pescuitul pe acest lac (ex: Permis obligatoriu, Se permite pescuitul din barcă, Program: 06:00-22:00)', verbose_name='Reguli de pescuit'),
        ),
    ]
