# Generated by Django 5.1.6 on 2025-06-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_lake_google_maps_embed_lake_lake_type_and_more'),
    ]

    operations = [
    ]
