# Generated by Django 5.1.6 on 2025-06-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_facility_fishspecies_remove_lake_fish_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='slug',
            field=models.SlugField(default=1, help_text='URL-ul prietenos pentru lac (se generează automat din nume)', max_length=250, unique=True, verbose_name='URL slug'),
            preserve_default=False,
        ),
    ]
