# Generated by Django 5.1.6 on 2025-06-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_lake_slug'),
    ]

    operations = [
    ]
