# Generated by Django 5.1.6 on 2025-06-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_add_lake_photo_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lakephoto',
            unique_together=set(),
        ),
    ]
