# Generated by Django 5.1.5 on 2025-02-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_brand_productattribute_productreview_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lake',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lake',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
