# Generated by Django 5.1.5 on 2025-02-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_lake_latitude_alter_lake_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/logo.png', null=True, upload_to='avatars/'),
        ),
    ]
