# Generated by Django 5.1.5 on 2025-02-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolunarPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('moon_phase', models.FloatField(help_text='0-1 pentru faza lunii')),
                ('major_start', models.TimeField()),
                ('major_end', models.TimeField()),
                ('minor_start', models.TimeField()),
                ('minor_end', models.TimeField()),
                ('rating', models.FloatField(help_text='1-5 pentru calitatea pescuitului')),
            ],
            options={
                'verbose_name': 'Predicție solunară',
                'verbose_name_plural': 'Predicții solunar',
                'ordering': ['date'],
            },
        ),
    ]
