# Generated by Django 5.0.1 on 2025-02-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_lake_model'),
        ('main', '0025_add_brasov_lakes'),
    ]

    operations = [
    ]
