# Generated by Django 5.0.1 on 2025-02-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_add_counties_data'),
        ('main', '0026_merge_0024_lake_model_0025_add_brasov_lakes'),
    ]

    operations = [
    ]
